\echo  'INSERTION_JEUX_OLYMPIQUES'

INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('STOCKHOLM', 1912, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('BERLIN', 1916, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('ANVERS', 1920, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('PARIS', 1924, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('AMSTERDAM', 1928, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('LOS ANGELES', 1932, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('BERLIN', 1936, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('LONDRES', 1948, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('HELSINKI', 1952, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('MELBOURNE', 1956, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('ROME', 1960, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('TOKYO', 1964, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('MEXICO', 1968, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('MUNICH', 1972, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('MONTREAL', 1976, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('MOSCOU', 1980, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('LOS ANGELES', 1984, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('SEOUL', 1988, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('BARCELONE', 1992, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('ATLANTA', 1996, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('SYDNEY', 2000, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('ATHENES', 2004, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('PEKIN', 2008, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('LONDRES', 2012, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('RIO DE JANEIRO', 2016, 'ETE');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('PARIS', 2024, 'ETE');


INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('LILLEHAMMER', 1994, 'HIVER');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('NAGANO', 1998, 'HIVER');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('SALTE LAKE CITY', 2002, 'HIVER');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('TURIN', 2006, 'HIVER');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('VANCOUVRE', 2010, 'HIVER');
INSERT INTO JEUX_OLYMPIQUES (VILLE, ANNEE, TYPE_EDITION) VALUES ('SOTCHI', 2014, 'HIVER');


\echo  'INSERTION_EPREUVES'


INSERT INTO EPREUVES VALUES ('ATHLETISME', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('BOXE', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('ESCRIME', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('JUDO', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('PATINAGE ARTISTIQUE', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('SAUT A SKI', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('TENNIS', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('PLONGEON', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('NATATION', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('TAEKWONDO', 'INDIVIDUELLE');
INSERT INTO EPREUVES VALUES ('LUTTE_LIBRE', 'INDIVIDUELLE');

INSERT INTO EPREUVES VALUES ('AVIRON', 'EN EQUIPE');
INSERT INTO EPREUVES VALUES ('BASKET-BALL','EN EQUIPE');
INSERT INTO EPREUVES VALUES ('ESCRIME', 'EN EQUIPE');
INSERT INTO EPREUVES VALUES ('HOCKEY', 'EN EQUIPE');
INSERT INTO EPREUVES VALUES ('FOOTBALL', 'EN EQUIPE');
INSERT INTO EPREUVES VALUES ('TENNIS', 'EN EQUIPE');
INSERT INTO EPREUVES VALUES ('HANDBALL', 'EN EQUIPE');
INSERT INTO EPREUVES VALUES ('NATATION', 'EN EQUIPE');
INSERT INTO EPREUVES VALUES ('VOLLEYBALL', 'EN EQUIPE');
INSERT INTO EPREUVES VALUES ('BOBSLEIGH', 'EN EQUIPE');

\echo  'INSERTION_SUB_EPREUVES'


-------------- ATHLETHISME -------------------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', '100M M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', '110M M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', '200M M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', '400M M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', 'MARATHON M');
-------------------------------------------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', '100M F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', '110M F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', '200M F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ATHLETISME', '400M F');

-------------- BOXE  -------------------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BOXE', 'MI_MOUCHE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BOXE', 'MOUCHE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BOXE', 'COQ M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BOXE', 'LEGERS M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BOXE', 'SUPER_LEGERS M');

INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BOXE', 'LEGERS F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BOXE', 'MOUCHE F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BOXE', 'MOYENS F');

-------------- NATATION  -------------------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '100M_BRASSE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '100M_DOS M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '100M_NAGE_LIBRE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '200M_NAGE_LIBRE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '100M_PAPILLON M');

INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '200M_BRASSE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '200M_DOS M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '400M_NAGE_LIBRE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '1500M_NAGE_LIBRE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '200M_PAPILLON M');

INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '100M_BRASSE F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '100M_DOS F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '100M_NAGE_LIBRE F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '100M_PAPILLON F');

INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '200M_BRASSE F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '200M_DOS F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '200M_NAGE_LIBRE F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('NATATION', '200M_PAPILLON F');

-------------- BASKET-BALL--------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BASKET-BALL', 'M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('BASKET-BALL', 'F');

-------------- FOOTBALL--------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('FOOTBALL', 'M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('FOOTBALL', 'F');


-------------- HANDBALL--------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('HANDBALL', 'M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('HANDBALL', 'F');

-------------- VOLLEYBALL--------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('VOLLEYBALL', 'M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('VOLLEYBALL', 'F');


-------------- AVIRON --------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('AVIRON', 'DEUX_SANS_BARREUR M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('AVIRON', 'QUATRE_SANS_BARREUR M');

-------------- JUDO --------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('JUDO', 'MOIN_DE_66kg M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('JUDO', 'MOIN_DE_52kg F');

-------------- ESCRIME --------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ESCRIME', 'EPEE_PAR_EQUIPE M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ESCRIME', 'FLEURET_INDIVIDUEL M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ESCRIME', 'EPEE_INDIVIDUEL F');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('ESCRIME', 'FLEURET_INDIVIDUEL F');

-------------- LUTTE_LIBRE --------------------------
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('LUTTE_LIBRE', 'MOIN_DE_65kg M');
INSERT INTO SUB_EPREUVES (NOM_EPREUVE, DETAIL) VALUES ('LUTTE_LIBRE', 'MOIN_DE_52kg F');


\echo  'INSERTIONS_EQUIPES'

---------------------- Quelques EQUIPES ------------------------------

------------------ FOOTBALL HOMMES---------------------------------------

insert into EQUIPES(PAYS) values ('United States');
insert into EQUIPES(PAYS) values ('Spain');
insert into EQUIPES(PAYS) values ('Argentina');
insert into EQUIPES(PAYS) values ('Italy');


------------------ HANDBALL Hommes ---------------------------------------

insert into EQUIPES(PAYS) values ('France');
insert into EQUIPES(PAYS) values ('Brasil');
insert into EQUIPES(PAYS) values ('Korea South');
insert into EQUIPES(PAYS) values ('United Kingdom');

------------------ HANDBALL FEMMES ---------------------------------------

insert into EQUIPES(PAYS) values ('France');
insert into EQUIPES(PAYS) values ('Brasil');
insert into EQUIPES(PAYS) values ('Korea South');
insert into EQUIPES(PAYS) values ('United Kingdom');
